create table country (
    id bigint generated by default as identity primary key,
    name varchar(255),
    continent varchar(255)
);

create table author (
    id bigint generated by default as identity primary key,
    name varchar(255),
    surname varchar(255),
    country_of_origin bigint,
    constraint fk_country foreign key (country_of_origin) references country
);

create table book (
    id bigint generated by default as identity primary key,
    name varchar(255),
    category int,
    author bigint,
    available_copies int,
    constraint fk_author foreign key (author) references author
);

create table library_users(
id bigint generated by default as identity primary key,
username    varchar(255),
password        varchar(255),
is_account_non_expired     boolean default true,
is_account_non_locked      boolean default true,
is_credentials_non_expired boolean default true,
is_enabled                 boolean default true,
role                       varchar(50)
);

create table users_books(
    record_id bigint generated by default as identity primary key,
    user_id bigint references library_users,
    book_id bigint references book
);